# Generated by Django 2.2.12 on 2022-08-05 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100, unique=True)),
                ('location', models.CharField(max_length=100)),
                ('weather_icon', models.CharField(max_length=80)),
                ('weather_info', models.CharField(max_length=64)),
                ('temperature', models.CharField(max_length=16)),
                ('visibility', models.CharField(max_length=16)),
                ('humidity', models.CharField(max_length=16)),
                ('dew_point', models.CharField(max_length=16)),
                ('date', models.CharField(max_length=16)),
                ('cur_time', models.TimeField()),
            ],
        ),
    ]
