# Generated by Django 2.2.12 on 2022-09-02 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='weather',
            options={'verbose_name_plural': 'Weather'},
        ),
    ]
