# Generated by Django 3.2.15 on 2022-10-16 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0002_auto_20220902_0256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weather',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
