# Generated by Django 2.2.12 on 2022-08-16 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='likestatus',
            table='story_like_status',
        ),
        migrations.AlterModelTable(
            name='story',
            table='story_story',
        ),
    ]
