# Generated by Django 2.2.12 on 2022-08-17 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0002_auto_20220816_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='like',
            field=models.ManyToManyField(related_name='story_like', to='user.UserProfile'),
        ),
        migrations.AlterField(
            model_name='story',
            name='view',
            field=models.IntegerField(default=0),
        ),
    ]
