# Generated by Django 2.2.12 on 2022-09-02 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0003_auto_20220817_1617'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='likestatus',
            options={'verbose_name': 'Like Status', 'verbose_name_plural': 'Like Status'},
        ),
        migrations.AlterModelOptions(
            name='story',
            options={'verbose_name': 'Story', 'verbose_name_plural': 'Stories'},
        ),
    ]
