# Generated by Django 3.2.15 on 2022-10-16 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0004_auto_20220902_0256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='updated_time',
            field=models.DateTimeField(),
        ),
    ]
