# Generated by Django 3.2.15 on 2022-10-16 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0005_alter_story_updated_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likestatus',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='story',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
