# Generated by Django 2.2.12 on 2022-08-16 16:38

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('google_id', models.IntegerField(null=True, unique=True)),
                ('google_pic', models.CharField(max_length=255, null=True)),
                ('username', models.CharField(max_length=128, unique=True)),
                ('password', models.CharField(max_length=128, null=True, unique=True)),
                ('first_name', models.CharField(max_length=128)),
                ('last_name', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('avatar', models.ImageField(null=True, upload_to='avatar')),
                ('background_img', models.ImageField(null=True, upload_to='background')),
                ('profile_name', models.CharField(default='My Profile Name', max_length=128)),
                ('motto', models.CharField(default=user.models.default_motto, max_length=128)),
                ('self_intro', models.TextField(default='')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'user_user_profile',
            },
        ),
    ]
