# Generated by Django 2.2.12 on 2022-08-16 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='google_id',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
